In [1]:
# ==========================================================
# Import Libraries
# ==========================================================

from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

In [2]:
# ==========================================================
# Load Data
# ==========================================================

DATA_PATH = (
    Path("../data/processed/BTCUSDT/BTCUSDT_1m_clean.csv")
)

df = pd.read_csv(
    DATA_PATH,
    parse_dates=["open_time", "close_time"]
)

# ==========================================================
# Preview Data
# ==========================================================

df.head()

            open_time      open      high       low     close    volume              close_time  quote_asset_volume  number_of_trades  taker_buy_base_volume  taker_buy_quote_volume  ignore
0 2025-01-01 00:00:00  93576.00  93610.93  93537.50  93610.93   8.21827 2025-01-01 00:00:59.999        7.689788e+05              2631                3.95157           369757.326529       0
1 2025-01-01 00:01:00  93610.93  93652.00  93606.20  93652.00  12.14029 2025-01-01 00:01:59.999        1.136551e+06              1273                4.08887           382791.500172       0
2 2025-01-01 00:02:00  93652.00  93702.15  93635.98  93702.15  11.60597 2025-01-01 00:02:59.999        1.087101e+06              1095                5.86840           549682.868570       0
3 2025-01-01 00:03:00  93702.14  93702.15  93654.48  93677.98   8.72958 2025-01-01 00:03:59.999        8.177203e+05              1461                2.48203           232486.113080       0
4 2025-01-01 00:04:00  93677.98  93677.99  93659.92  93661.20   5.24749 2025-01-01 00:04:59.999        4.915570e+05               988                0.48880            45786.251963       0

In [3]:
# ==========================================================
# Create Target
# ==========================================================

df["target"] = (
    df["close"].shift(-1) > df["close"]
).astype(int)

# Xóa dòng cuối cùng vì không có nến tiếp theo
df = df.iloc[:-1].copy()

# Kiểm tra
df[["close", "target"]].head(10)

      close  target
0  93610.93       1
1  93652.00       1
2  93702.15       0
3  93677.98       0
4  93661.20       1
5  93678.01       0
6  93632.05       0
7  93612.01       0
8  93611.84       0
9  93607.10       0

In [4]:
# ==========================================================
# Save Dataset with Target
# ==========================================================

OUTPUT_PATH = Path("../data/processed/BTCUSDT/BTCUSDT_1m_target.csv")

df.to_csv(
    OUTPUT_PATH,
    index=False
)

print(f"Saved to: {OUTPUT_PATH}")
print(df.shape)

Saved to: ..\data\processed\BTCUSDT\BTCUSDT_1m_target.csv
(20160, 13)