In [1]:
import pandas as pd

In [2]:
FEATURE_PATH = r"D:\Subject\CV2026\Market Risk Classification\market-risk-classification\data\feature_store\BTCUSDT\BTCUSDT_feature_store.parquet"

In [3]:
df_feature = pd.read_parquet(
    FEATURE_PATH
)

In [4]:
df_feature.shape

(1999017, 77)

In [5]:
df_feature.head()

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_volume,...,close_lag_3,volume_lag_1,volume_lag_2,volume_lag_3,RSI_14_lag_1,RSI_14_lag_2,RSI_14_lag_3,MACD_lag_1,MACD_lag_2,MACD_lag_3
0,2017-08-17 05:39:00,4291.37,4291.37,4291.37,4291.37,0.134767,2017-08-17 05:39:59.999,578.335061,1,0.0,...,4320.00,0.098390,0.373933,0.019386,54.934206,54.934206,54.934206,1.040049,1.116026,1.196767
1,2017-08-17 05:40:00,4291.37,4291.37,4291.37,4291.37,0.000000,2017-08-17 05:40:59.999,0.000000,0,0.0,...,4320.00,0.134767,0.098390,0.373933,16.876822,54.934206,54.934206,-1.315204,1.040049,1.116026
2,2017-08-17 05:41:00,4291.37,4291.37,4291.37,4291.37,0.000000,2017-08-17 05:41:59.999,0.000000,0,0.0,...,4320.00,0.000000,0.134767,0.098390,16.876822,16.876822,54.934206,-3.145500,-1.315204,1.040049
3,2017-08-17 05:42:00,4291.37,4291.37,4291.37,4291.37,0.000000,2017-08-17 05:42:59.999,0.000000,0,0.0,...,4291.37,0.000000,0.000000,0.134767,16.876822,16.876822,16.876822,-4.543646,-3.145500,-1.315204
4,2017-08-17 05:43:00,4291.37,4291.37,4291.37,4291.37,0.000000,2017-08-17 05:43:59.999,0.000000,0,0.0,...,4291.37,0.000000,0.000000,0.000000,16.876822,16.876822,16.876822,-5.587280,-4.543646,-3.145500

In [6]:
df_feature.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999017 entries, 0 to 1999016
Data columns (total 77 columns):
 #   Column                  Dtype
---  ------                  -----
 0   open_time               datetime64[ns]
 1   open                    float64
 2   high                    float64
 3   low                     float64
 4   close                   float64
 5   volume                  float64
 6   close_time              datetime64[ns]
 7   quote_asset_volume      float64
 8   number_of_trades        int64
 9   taker_buy_base_volume   float64
 10  taker_buy_quote_volume  float64
 11  ignore                  int64
 12  SMA_5                   float64
 13  SMA_10                  float64
 14  SMA_20                  float64
 15  SMA_50                  float64
 16  SMA_100                 float64
 17  EMA_5                   float64
 18  EMA_10                  float64
 19  EMA_20                  float64
 20  EMA_50                  float64
 21  EMA_100                 float64
 22  RSI_7                   float64
 23  RSI_14                  float64
 24  RSI_21                  float64
 25  ROC_5                   float64
 26  ROC_10                  float64
 27  Momentum_5              float64
 28  Momentum_10             float64
 29  MACD                    float64
 30  MACD_signal             float64
 31  MACD_hist               float64
 32  BB_upper_20             float64
 33  BB_middle_20            float64
 34  BB_lower_20             float64
 35  BB_width_20             float64
 36  ATR_14                  float64
 37  ATR_28                  float64
 38  Volatility_5            float64
 39  Volatility_10           float64
 40  Volatility_20           float64
 41  Volatility_50           float64
 42  OBV                     float64
 43  VWAP                    float64
 44  Volume_MA_5             float64
 45  Volume_MA_10            float64
 46  Volume_MA_20            float64
 47  Return_1                float64
 48  Log_Return_1            float64
 49  Return_5                float64
 50  Log_Return_5            float64
 51  Return_10               float64
 52  Log_Return_10           float64
 53  Rolling_Mean_5          float64
 54  Rolling_STD_5           float64
 55  Rolling_Mean_10         float64
 56  Rolling_STD_10          float64
 57  Rolling_Mean_20         float64
 58  Rolling_STD_20          float64
 59  hour                    int32
 60  minute                  int32
 61  day                     int32
 62  month                   int32
 63  day_of_week             int32
 64  week_of_year            int64
 65  close_lag_1             float64
 66  close_lag_2             float64
 67  close_lag_3             float64
 68  volume_lag_1            float64
 69  volume_lag_2            float64
 70  volume_lag_3            float64
 71  RSI_14_lag_1            float64
 72  RSI_14_lag_2            float64
 73  RSI_14_lag_3            float64
 74  MACD_lag_1              float64
 75  MACD_lag_2              float64
 76  MACD_lag_3              float64
dtypes: datetime64[ns](2), float64(67), int32(5), int64(3)
memory usage: 1.1 GB

In [7]:
features = df_feature.columns.tolist()

len(features), features

(77,
 ['open_time',
  'open',
  'high',
  'low',
  'close',
  'volume',
  'close_time',
  'quote_asset_volume',
  'number_of_trades',
  'taker_buy_base_volume',
  'taker_buy_quote_volume',
  'ignore',
  'SMA_5',
  'SMA_10',
  'SMA_20',
  'SMA_50',
  'SMA_100',
  'EMA_5',
  'EMA_10',
  'EMA_20',
  'EMA_50',
  'EMA_100',
  'RSI_7',
  'RSI_14',
  'RSI_21',
  'ROC_5',
  'ROC_10',
  'Momentum_5',
  'Momentum_10',
  'MACD',
  'MACD_signal',
  'MACD_hist',
  'BB_upper_20',
  'BB_middle_20',
  'BB_lower_20',
  'BB_width_20',
  'ATR_14',
  'ATR_28',
  'Volatility_5',
  'Volatility_10',
  'Volatility_20',
  'Volatility_50',
  'OBV',
  'VWAP',
  'Volume_MA_5',
  'Volume_MA_10',
  'Volume_MA_20',
  'Return_1',
  'Log_Return_1',
  'Return_5',
  'Log_Return_5',
  'Return_10',
  'Log_Return_10',
  'Rolling_Mean_5',
  'Rolling_STD_5',
  'Rolling_Mean_10',
  'Rolling_STD_10',
  'Rolling_Mean_20',
  'Rolling_STD_20',
  'hour',
  'minute',
  'day',
  'month',
  'day_of_week',
  'week_of_year',
  'close_lag_1',
  'close_lag_2',
  'close_lag_3',
  'volume_lag_1',
  'volume_lag_2',
  'volume_lag_3',
  'RSI_14_lag_1',
  'RSI_14_lag_2',
  'RSI_14_lag_3',
  'MACD_lag_1',
  'MACD_lag_2',
  'MACD_lag_3'])

In [8]:
df_feature.isnull().sum().sort_values(
    ascending=False
).head(20)

open_time                 0
open                      0
high                      0
low                       0
close                     0
volume                    0
close_time                0
quote_asset_volume        0
number_of_trades          0
taker_buy_base_volume     0
taker_buy_quote_volume    0
ignore                    0
SMA_5                     0
SMA_10                    0
SMA_20                    0
SMA_50                    0
SMA_100                   0
EMA_5                     0
EMA_10                    0
EMA_20                    0
dtype: int64

In [9]:
df_feature.describe().T

,count,mean,min,25%,50%,75%,max,std
open_time,1999017,2019-07-16 09:10:13.497634048,2017-08-17 05:39:00,2018-08-02 12:20:00,2019-07-16 18:05:00,2020-06-28 22:44:00,2021-06-11 17:21:00,NaN
open,1999017.0,13011.663704,2830.0,6525.47,8685.19,11315.29,64800.0,13257.461902
high,1999017.0,13022.172639,2830.0,6529.17,8691.93,11323.34,64854.0,13269.659176
low,1999017.0,13000.9587,2817.0,6521.58,8678.7,11306.54,64685.17,13245.338444
close,1999017.0,13011.656047,2817.0,6525.34,8685.2,11315.27,64800.0,13257.479942
...,...,...,...,...,...,...,...,...
RSI_14_lag_2,1999017.0,50.323986,0.038198,43.232163,50.362795,57.424773,99.820322,10.896287
RSI_14_lag_3,1999017.0,50.323981,0.038198,43.232163,50.362795,57.424772,99.820322,10.896282
MACD_lag_1,1999017.0,0.113413,-1367.102499,-3.539262,0.15334,3.981354,991.304138,28.362981
MACD_lag_2,1999017.0,0.113378,-1367.102499,-3.539143,0.153336,3.981274,991.304138,28.362938
MACD_lag_3,1999017.0,0.113344,-1367.102499,-3.539007,0.153319,3.981134,991.304138,28.362896